### ISSUE TITLE
Convert existing encoded credential to Bcrypt?

### ISSUE THREAD

**Issue by rehmke** [Wolf480pl/PHPass#3] opened 2018-06-06 20:40 UTC
Hello,

    I have a number of encoded passwords that look something like the following (representative example from WordPress):

        $P$BMYJOjzPjlG031l1/fjc938A88RsFi/

    Could your library be used to convert the existing encoded passwords to an encoding via Bcrypt?  

    For completeness, I am using your library and the following to generate hashed passwords now:

        PHPass pw = new PHPass(8);
        String hpw = pw.HashPassword("FOOBAR");

    Please advise, and thank you.

Best regards,

rehmke

**Comment by Wolf480pl** [comment] 2018-06-06 21:11
>[Can I] convert the existing encoded passwords to an encoding via Bcrypt?

Unfortunately, you can't. In theory, it should be impossible, no matter what library you use.

Hash functions, by definition, cannot be inverted.
When you have a  PHPass hash of password.
BCrypt is a different hash function than PHPass, so to calculate BCrypt(password), you would need to get the plaintext password first. But to get to it, you'd need to invert PHPass, which is meant to be impossible. If you found a way to do it, that'd be an attack against the PHPass algorithm, and it'd mean PHPass is broken and useless.

Now, what you could to is use the new hash (BCrypt) for all the new passwords.
Then you could ask all your users to change their passwords, and even if they change to the same password they had before, you'll be able to hash them with BCrypt instead of PHPass.

Anyway, the issue isn't related to the library, so I'm gonna close it.
If you have further questions, you can still ask them, but I'm pretty busy this week so don't expect quick answers.

**Closed as completed by Wolf480pl** 2018-06-06 21:11 UTC

**Comment by rehmke** [comment] 2018-06-06 21:19
I understand - not an issue with the library to be sure, I simply had a
question.

The only reason that I asked was the following website purported that it
would be possible to effectively re-encode using BCrypt (while retaining
MD5?):

http://john.cuppi.net/migrate-from-md5-to-bcrypt-password-hashes/

Thank you

**Comment by Wolf480pl** [comment] 2018-06-06 22:12
oh, they just use md5(password) as password, and store BCrpyt(md5(password))... clever.
Yeah, you can do this. But ofc this requires you to change the way your application verifies passwords
